### ISSUE TITLE
Install instructions on anaconda don't work

### ISSUE THREAD

**Issue by sverhoeven** [iomega/spec2vec#10]
The install instructions on https://anaconda.org/nlesc/spec2vec don't work.

Trying

```shell
conda install -c nlesc spec2vec
```

It is unable to find the dependencies.

The install command `conda install --channel nlesc --channel bioconda --channel conda-forge spec2vec` in the README.md does work.

We should somehow make sure the install instructions on https://anaconda.org/nlesc/spec2vec work or are corrected in the description.

**Comment by florian-huber** [comment]
Outdated, if still an issue please reopen.
