### ISSUE TITLE
Specify SpectrumType without importing matchms

### ISSUE THREAD

**Issue by florian-huber** [iomega/spec2vec#18]
The original idea was to keep spec2vec to some extend independent of matchms to allow people to use it for different types of data.
How do we best specify the ``Spectrum`` input type for ``SpectrumDocument``  without importing matchms? Use the docstring instead of typing?

**Comment by jspaaks** [comment]
Note: matchms is purposely not a dependency of spec2vec:
https://github.com/iomega/spec2vec/blob/67c46294835c593cbc69f62443c6177fe26d969c/conda/environment.yml#L7-L10

For other types of data, people can make their own classes, inheriting from ``Document`` just like ``SpectrumDocument`` does.

For example, for gene sequence data you may have
```python
class SequenceDocument(Document):
    def __init__(self, sequence, some_parameter="somevalue"):
      self.some_parameter = some_parameter
      self.member = None
      super().__init__(obj=sequence)
      self.some_method()

   def some_method(self):
      self.member = "some value"
      return self
```

**Comment by florian-huber** [comment]
@jspaaks I agree, and that's why I would also like to avoid importing matchms here.

It still would be nice to link to matchms for the expected ``spectrum`` input in ``SpectrumDocuments``. Maybe we can simply specify this in the docstring.

**Comment by sverhoeven** [comment]
But matchms is included in conda/environment-dev.yml for the tests.

I don't get your avoidance for making matchms a dependency of spec2vec. Spec 2 vec implememts methods to convert a matchms Spectrum to word vectors. So for me it is not weird to point to matchms to describe that. Also examples in doc strings will need to show where the spectrum comes from.  It would result in less surprises when matchms is already installed.

**Comment by florian-huber** [comment]
For me the issue is not so much matchms itself. I mostly worry about its dependencies, first of all ``rdkit``. 

In principle , we want people to also use spec2vec for entirely different data (and I expect we will also use it on gene data/BGCs). For such cases, having all the mass-spec specific imports seem unnecessary ballast to me.

To the test:
Those indeed need parts of matchms! I was assuming that since it is only used in the dev-environment that should be fine. Or does that make things more complicated?

**Comment by florian-huber** [comment]
outdated. Matchms has just become a dependency (which in the future it will hopefully be a more lightweight dependency).
