### ISSUE TITLE
pylint fails - seems analoge to what happend to matchms before

### ISSUE THREAD

**Issue by florian-huber** [iomega/spec2vec#23]

**Comment by sverhoeven** [comment]
So https://github.com/matchms/matchms/commit/45f8f9a6bda3944cb99d951eae7facc9ce176d5e might also fix it here

**Comment by florian-huber** [comment]
Yes, I believe so. Will check this today.

**Comment by florian-huber** [comment]
--> PR #24

**Comment by florian-huber** [comment]
That solved it. (see PR #24 )
