### ISSUE TITLE
Create RSD page

### ISSUE THREAD

**Issue by sverhoeven** [iomega/spec2vec#25]
It would be nice if to add spec2vec to https://www.research-software.nl/ . 

The RSD needs some text for the target audience and strengths. This text could be also added to the main README and docs.

**Comment by sverhoeven** [comment]
There already is a draft entry which should be enhanced and published

**Comment by florian-huber** [comment]
I added more information and published it.

**Comment by florian-huber** [comment]
spec2vec is now part of RSD.

**Comment by jspaaks** [comment]
Nice! Couple of requests:
- could you use the conceptDOI? It's now the versioned DOI (Also for ``matchms`` BTW)
- are there any mentions that we can add? For example, I see existing mentions that point to the conda packages for (both for matchms and spec2vec), and in the readme https://github.com/iomega/spec2vec/blob/master/README.rst I see here are DOIs to papers, which you can add to Zotero, then ([wait for a bit and](https://www.research-software.nl/schedule/)) add them as mentions to spec2vec and matchms respectively.

**Comment by florian-huber** [comment]
(Seems my quick closing trick did not work...)
But for real: Thanks Jurriaan, I'll added the conceptDOIs instead. Thought I had done that, but copy+pasted the wrong ones first.

And I just added the 2 preprints to zotero and will add all the mentions tomorrow once they are in the RSD.

**Comment by florian-huber** [comment]
Still don't see the new mentions in the list... will try it another time.

**Comment by jspaaks** [comment]
In Zotero, the mentions need to be in a folder (any one will do). I've now put them in 27017G01. I can see them appear as mentions, but haven't linked them yet. Your move Huber :)

**Comment by florian-huber** [comment]
Alright!
So I finally received the deserved punishment for being lazy and not putting things in the right folders.
I added the mentions (and a new contributor) on RSD!

**Comment by jspaaks** [comment]
Looking good sir

I had to update the DOI for matchms BTW 

Also, note you don't have to add software items such as https://www.zotero.org/groups/1689348/netherlands_escience_center/items/WZAPMFUE to Zotero, that is what we have the RSD for. 

If nothing else works, [RTM](https://github.com/research-software-directory/research-software-directory/blob/master/docs/instruction/zotero.md#software)

**Comment by florian-huber** [comment]
Perfect, thanks!
And for the software item I just confused, because I only found a very old item for ``mcfly v1.0.4`` but was expecting something newer.

Anyway, guess I can close this issue (right?).

**Comment by florian-huber** [comment]
Thanks for bringing this up! The spec2vec RSD page is now implemented, so I will close this.
