### ISSUE TITLE
Conda publish workflow fails

### ISSUE THREAD

**Issue by florian-huber** [iomega/spec2vec#65]
For the newest release the Anaconda publish workflow failed https://github.com/iomega/spec2vec/runs/2857157873?check_suite_focus=true

Unfortunately, the error message is not particularly helpful. 

I re-ran the workflow (nothing changed) and spotted one change we should make (#64) but which I assume will not change much.
Any ideas on this @sverhoeven ?

**Comment by sverhoeven** [comment]
The ANACONDA_TOKEN has a default expiration data of a year and that year has passed. The token needs to be regenerated

**Comment by sverhoeven** [comment]
I regenerated the token with API read/write scope, set in GH settings and restarted the workflow

**Comment by sverhoeven** [comment]
Success, 0.5.0 is on https://anaconda.org/nlesc/spec2vec/files

**Comment by florian-huber** [comment]
Nice, thanks a lot Stefan (I wasn't aware that those tokens expire...)!

I will close this issue.
