### ISSUE TITLE
Two test failing with conda package and ubuntu

### ISSUE THREAD

**Issue by florian-huber** [iomega/Spec2Vec#83]
Last merge #81 was a bit too quick (my fault).
Turns out that two Conda Verify tests fail in `test_model_serialization` (see [here](https://github.com/iomega/spec2vec/actions/runs/3164781545/jobs/5153418336)).

Could you have a look at this @maximskorik ?
(I also just gave you writing rights for this repository)

**Comment by maximskorik** [comment]
Solved and merged into `master` with #85.
