### ISSUE TITLE
reduce the size score after calling calculate_stores

### ISSUE THREAD

**Issue by r00bit** [iomega/Spec2Vec#86]
Hi, 
After training spec2vec model and creating spec2vec_similarity function, I used calculate_scores to find the similarity of spectra pairs
scores = calculate_scores(reference_documents, query_spectrums, spec2vec_similarity)
However the size scores is too big to process it, how can I reduce the size of scores by saving only the non-zero scores with their related reference and query scan numbers?
Thanks!

**Comment by florian-huber** [comment]
We are currently working on such a sparse implementation. I *hope* this will be ready very soon (few weeks... again: I hope).

**Comment by florian-huber** [comment]
Done and outdated.
